### ISSUE TITLE
Minutes are not correctly calculated as per timezone

### ISSUE THREAD

**Issue by darshan-shah-git** [troglobit/sun#1]
Hi,
In convert() function of sunrise.c file, difference is not correctly added.
As example, if my timezone is +5:30, then current logic is only adding +5 Hr only. We need to add logic to add correct minutes details.
Updated Code:
```
static void convert(double ut, int *h, int *m)
{
   *h = (int)floor(ut);
   *m = (int)(60 * (ut - floor(ut)));

   *m += (timediff() % 3600)/60;
   *h += timediff() / 3600;
}
```

**Comment by troglobit** [comment]
Cool, never even heard about "half" timezones before! :)

Would you mind doing a pull request?

**Comment by darshan-shah-git** [comment]
I have created Pull request. Thank you!!


Regards,
Darshan Shah
________________________________

**Comment by troglobit** [comment]
Merged to master :)
